[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["node"]

[[build.nixpacksPlan.phases]]
name = "install"
nixPkgsArchive = "ba913eda2df8eb72147259189d55932012df6301"
cmds = ["npm ci"]

[[build.nixpacksPlan.phases]]
name = "build"
cmds = ["npm run docs:build"]

[deploy]
startCommand = "npm run docs:preview -- --port $PORT --host 0.0.0.0"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

